TO DO
========================================================

## Open issues:

- If I use variables from previous exercises make sure they exist.
- Think of rewards, points etc.


## Partly done issues
- Hints:
  - In tests you can add hints by specifying the hint.name argument.
  - If a test with a hint fails, the student can type hint() in the R console to see the hint that was specified for this test.
  - So far we can only save one hint per test, but that should be easy to mend later.

- Intermediate success messages
  - Mostly done, added tests have an argument success.message that shows this message the first time the test is correctly passed
  
- If an exercise code was not changed, jump to another exercise whose code has been changed! If not other code was changed, stay with the exercise
  - Partially done. Probably needs some more checking


## Closed issues:

- check.var: Message wrong length, has no variable name
  - Done
- check.var: Add manual error messages in check.var
  - Done, added parameters for manual messages

- RTutor must load restorepoint
  - Done